# Generated by Django 6.0.6 on 2026-06-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_approved_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin approval required for login'),
        ),
    ]
